### ISSUE TITLE
Unable to import Monokai Soda Custom.terminal

### ISSUE THREAD

**Issue by cmavromichalis** [cmilr/Git-Beautify-For-MacOS-Terminal#4]
I tried to import this theme as it looks pretty cool but I can't. I am not given the option to select it when I go Terminal -> Preferences -> Profiles -> Import

I exported existing themes and am able to Import them. I tried renaming the .terminal file without spaces but no luck. I also made the permissions on the file the same as the ones I was able to export.

I am on Mac OS High Sierra Version 10.13.3

<img width="315" alt="screen shot 2018-04-05 at 11 17 12 am" src="https://user-images.githubusercontent.com/15347540/38381122-0df06fde-38c3-11e8-92e8-0b16d0b2294d.png">

**Comment by cmilr** [comment]
Ooh, strange. Thanks for the heads-up. I'll see if I can reproduce, and try to get you a fix.

**Comment by spaceforestchu** [comment]
Hi,
I imported but the color didn't change, but it changed in my macbook pro, but it didn't on my iMac.

Anything?

**Comment by cmavromichalis** [comment]
Apparently, I am dumb. User error.

I thought I could just save the file via Right Click, Save As, All Files. Seems doing that saved it as an HTML page with .terminal file type

Cloning the repository and importing works fine.

@spaceforestchu I'd recommend opening a new issue for your issues, I am closing this one.

**Comment by cmilr** [comment]
Glad you figured it out! ENJOY!
